services:
  hugo:
    image: hugomods/hugo:exts-0.154.5
    working_dir: /src
    volumes:
      - .:/src
    ports:
      - "1313:1313"
    command: ["server", "--bind", "0.0.0.0", "--port", "1313", "--baseURL", "http://localhost:1313/"]
